/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.incendie;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author thibautdesauty
 */
public class Accueil extends javax.swing.JFrame {

    private Simulation Sim;
    private int valTaille;
    private Terrain T_acc;
    private Vent V;

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //Creer un filtre qui ne sélectionnera que les fichiers .txt
        FileNameExtensionFilter ff = new FileNameExtensionFilter("Fichiers texte", "txt");
        jFCterrain.setFileFilter(ff);
    }

    public int getvalTaille() {
        return valTaille;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgVegetation = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        PVent = new javax.swing.JPanel();
        CbDirection = new javax.swing.JComboBox<>();
        CbForce = new javax.swing.JComboBox<>();
        LVent = new javax.swing.JLabel();
        LDirection = new javax.swing.JLabel();
        LForce = new javax.swing.JLabel();
        PHumidité = new javax.swing.JPanel();
        LTrès_sec = new javax.swing.JLabel();
        LSec = new javax.swing.JLabel();
        LNormal = new javax.swing.JLabel();
        LHumidité = new javax.swing.JLabel();
        SHumidite = new javax.swing.JSlider();
        PVegetation = new javax.swing.JPanel();
        RbClairsemée = new javax.swing.JRadioButton();
        RbEspacée = new javax.swing.JRadioButton();
        RbTouffue = new javax.swing.JRadioButton();
        RbContinue = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        bDemarrer_la_simulation = new javax.swing.JButton();
        bParametre = new javax.swing.JLabel();
        LTitre = new javax.swing.JLabel();
        jFCterrain = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLtaille = new javax.swing.JLabel();
        jSTaille = new javax.swing.JSlider();
        L100 = new javax.swing.JLabel();
        L150 = new javax.swing.JLabel();
        L20 = new javax.swing.JLabel();
        L60 = new javax.swing.JLabel();
        jLjBtelecharger = new javax.swing.JLabel();
        jLdev = new javax.swing.JLabel();
        jLnom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));

        PVent.setBackground(new java.awt.Color(0, 102, 51));
        PVent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(248, 201, 66), 2, true));
        PVent.setForeground(new java.awt.Color(248, 201, 66));

        CbDirection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nord", "Sud", "Est", "Ouest" }));
        CbDirection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbDirectionActionPerformed(evt);
            }
        });

        CbForce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nul", "Modéré", "Fort", "Violent" }));
        CbForce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbForceActionPerformed(evt);
            }
        });

        LVent.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        LVent.setForeground(new java.awt.Color(248, 201, 66));
        LVent.setText("Vent :");

        LDirection.setForeground(new java.awt.Color(248, 201, 66));
        LDirection.setText("Direction :");

        LForce.setForeground(new java.awt.Color(248, 201, 66));
        LForce.setText("Force :");

        javax.swing.GroupLayout PVentLayout = new javax.swing.GroupLayout(PVent);
        PVent.setLayout(PVentLayout);
        PVentLayout.setHorizontalGroup(
            PVentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PVentLayout.createSequentialGroup()
                .addGap(22, 22, Short.MAX_VALUE)
                .addGroup(PVentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PVentLayout.createSequentialGroup()
                        .addComponent(LDirection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CbDirection, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PVentLayout.createSequentialGroup()
                        .addComponent(LForce)
                        .addGap(18, 18, 18)
                        .addComponent(CbForce, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
            .addGroup(PVentLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(LVent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PVentLayout.setVerticalGroup(
            PVentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PVentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LVent)
                .addGap(18, 18, 18)
                .addGroup(PVentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDirection)
                    .addComponent(CbDirection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PVentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbForce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LForce))
                .addGap(14, 14, 14))
        );

        PHumidité.setBackground(new java.awt.Color(0, 102, 51));
        PHumidité.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 201, 66), 2));

        LTrès_sec.setForeground(new java.awt.Color(248, 201, 66));
        LTrès_sec.setText("Très sec");

        LSec.setForeground(new java.awt.Color(248, 201, 66));
        LSec.setText("Sec");

        LNormal.setForeground(new java.awt.Color(248, 201, 66));
        LNormal.setText("Normal");

        LHumidité.setForeground(new java.awt.Color(248, 201, 66));
        LHumidité.setText("Humidité");

        SHumidite.setForeground(new java.awt.Color(255, 255, 255));
        SHumidite.setMajorTickSpacing(20);
        SHumidite.setMaximum(4);
        SHumidite.setMinimum(1);
        SHumidite.setMinorTickSpacing(5);
        SHumidite.setOrientation(javax.swing.JSlider.VERTICAL);
        SHumidite.setPaintLabels(true);
        SHumidite.setPaintTicks(true);
        SHumidite.setToolTipText("");
        SHumidite.setValue(1);

        javax.swing.GroupLayout PHumiditéLayout = new javax.swing.GroupLayout(PHumidité);
        PHumidité.setLayout(PHumiditéLayout);
        PHumiditéLayout.setHorizontalGroup(
            PHumiditéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PHumiditéLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SHumidite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PHumiditéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHumiditéLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PHumiditéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PHumiditéLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(LNormal))
                            .addComponent(LSec)
                            .addComponent(LTrès_sec))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(PHumiditéLayout.createSequentialGroup()
                        .addComponent(LHumidité)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PHumiditéLayout.setVerticalGroup(
            PHumiditéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHumiditéLayout.createSequentialGroup()
                .addGroup(PHumiditéLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PHumiditéLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LHumidité)
                        .addGap(81, 81, 81)
                        .addComponent(LNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(LSec)
                        .addGap(81, 81, 81))
                    .addGroup(PHumiditéLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SHumidite, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(LTrès_sec)
                .addGap(14, 14, 14))
        );

        PVegetation.setBackground(new java.awt.Color(0, 102, 51));
        PVegetation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(248, 201, 66), 2, true));

        bgVegetation.add(RbClairsemée);
        RbClairsemée.setForeground(new java.awt.Color(248, 201, 66));
        RbClairsemée.setText("Clairsemée");
        RbClairsemée.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbClairseméeActionPerformed(evt);
            }
        });

        bgVegetation.add(RbEspacée);
        RbEspacée.setForeground(new java.awt.Color(248, 201, 66));
        RbEspacée.setText("Espacée");

        bgVegetation.add(RbTouffue);
        RbTouffue.setForeground(new java.awt.Color(248, 201, 66));
        RbTouffue.setText("Touffue");

        bgVegetation.add(RbContinue);
        RbContinue.setForeground(new java.awt.Color(248, 201, 66));
        RbContinue.setText("Continue");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 201, 66));
        jLabel1.setText("Densité de Vegetation :");

        javax.swing.GroupLayout PVegetationLayout = new javax.swing.GroupLayout(PVegetation);
        PVegetation.setLayout(PVegetationLayout);
        PVegetationLayout.setHorizontalGroup(
            PVegetationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PVegetationLayout.createSequentialGroup()
                .addGroup(PVegetationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PVegetationLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(PVegetationLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(PVegetationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RbEspacée)
                            .addComponent(RbClairsemée)
                            .addComponent(RbTouffue)
                            .addComponent(RbContinue))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PVegetationLayout.setVerticalGroup(
            PVegetationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PVegetationLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(RbClairsemée)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbEspacée)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RbTouffue)
                .addGap(12, 12, 12)
                .addComponent(RbContinue)
                .addGap(14, 14, 14))
        );

        bDemarrer_la_simulation.setBackground(new java.awt.Color(248, 201, 66));
        bDemarrer_la_simulation.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        bDemarrer_la_simulation.setText("Démarrer la simulation");
        bDemarrer_la_simulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDemarrer_la_simulationActionPerformed(evt);
            }
        });

        bParametre.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        bParametre.setForeground(new java.awt.Color(255, 255, 255));
        bParametre.setText("Paramètres :");

        LTitre.setFont(new java.awt.Font("Phosphate", 0, 24)); // NOI18N
        LTitre.setForeground(new java.awt.Color(255, 255, 255));
        LTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LTitre.setText("Simulation feu de forêt");
        LTitre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jFCterrain.setAcceptAllFileFilterUsed(false);
        jFCterrain.setBackground(new java.awt.Color(0, 153, 102));
        jFCterrain.setCurrentDirectory(new java.io.File("/Users/thibautdesauty/Documents/EPF/Cours EPF/2A/S4/CPO/ProjetS4_thibaut_desauty_hugo_de_miranda"));
        jFCterrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFCterrainActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 201, 66), 2));

        jLtaille.setForeground(new java.awt.Color(248, 201, 66));
        jLtaille.setText("Taille du terrain :");

        jSTaille.setForeground(new java.awt.Color(255, 255, 255));
        jSTaille.setMaximum(150);
        jSTaille.setMinimum(20);
        jSTaille.setValue(100);

        L100.setForeground(new java.awt.Color(248, 201, 66));
        L100.setText("100");

        L150.setForeground(new java.awt.Color(248, 201, 66));
        L150.setText("150");

        L20.setForeground(new java.awt.Color(248, 201, 66));
        L20.setText("20");

        L60.setForeground(new java.awt.Color(248, 201, 66));
        L60.setText("60");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSTaille, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLtaille)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(L20)
                        .addGap(52, 52, 52)
                        .addComponent(L60)
                        .addGap(51, 51, 51)
                        .addComponent(L100)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(L150)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLtaille)
                    .addComponent(L20)
                    .addComponent(L60)
                    .addComponent(L100)
                    .addComponent(L150))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSTaille, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLjBtelecharger.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jLjBtelecharger.setForeground(new java.awt.Color(255, 255, 255));
        jLjBtelecharger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLjBtelecharger.setText("ou télécharger un terrain ( en selectionnant un fichier puis en cliquant sur open)");

        jLdev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLdev.setText("Développé par :");

        jLnom.setText("Thibaut Desauty & Hugo De Miranda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bParametre)
                            .addComponent(PVent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PVegetation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PHumidité, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFCterrain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bDemarrer_la_simulation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLjBtelecharger, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(LTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLnom, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLdev, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(LTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLdev, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLnom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(bParametre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(PVegetation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PVent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(PHumidité, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bDemarrer_la_simulation, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLjBtelecharger)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFCterrain, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFCterrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFCterrainActionPerformed
        try {
            // TODO add your handling code here:
            T_acc = new Terrain(valTaille);
            String f = jFCterrain.getName(jFCterrain.getSelectedFile());
            T_acc = T_acc.Download(f);

            int valForce = 0;
            if (CbForce.getSelectedItem().equals("Nul")) {
                valForce = 0;
            } else if (CbForce.getSelectedItem().equals("Modéré")) {
                valForce = 1;
            } else if (CbForce.getSelectedItem().equals("Fort")) {
                valForce = 2;
            } else if (CbForce.getSelectedItem().equals("Violent")) {
                valForce = 3;
            }
            String valDirection = (String) CbDirection.getSelectedItem();
            V = new Vent(valDirection, valForce);

            T_acc.setNivHumidite(SHumidite.getValue());

            for (int j = 3; j < T_acc.Terrain.length - 3; j++) {
                switch (T_acc.getNivHumidite()) {
                    case 1:
                        T_acc.setProba_humidite(0.9);
                        break;
                    case 3:
                        T_acc.setProba_humidite(0.35);
                        break;
                    case 4:
                        T_acc.setProba_humidite(0.1);
                        break;
                    default:
                        T_acc.setProba_humidite(0.6);
                        break;
                }
            }
            Sim = new Simulation(this, false, T_acc.Terrain.length, T_acc, V);
            this.setVisible(false);
            Sim.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jFCterrainActionPerformed

    private void bDemarrer_la_simulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDemarrer_la_simulationActionPerformed
        // TODO add your handling code here:
        int densité = 100;
        if (RbClairsemée.isSelected()) {
            densité = 50;
        } else if (RbEspacée.isSelected()) {
            densité = 75;
        } else if (RbTouffue.isSelected()) {
            densité = 90;
        } else if (RbContinue.isSelected()) {
            densité = 100;
        }

        int valForce = 0;
        if (CbForce.getSelectedItem().equals("Nul")) {
            valForce = 0;
        } else if (CbForce.getSelectedItem().equals("Modéré")) {
            valForce = 1;
        } else if (CbForce.getSelectedItem().equals("Fort")) {
            valForce = 2;
        } else if (CbForce.getSelectedItem().equals("Violent")) {
            valForce = 3;
        }
        String valDirection = (String) CbDirection.getSelectedItem();
        V = new Vent(valDirection, valForce);
        valTaille = jSTaille.getValue();
        T_acc = new Terrain(valTaille);
        T_acc.setNivHumidite(SHumidite.getValue());

        T_acc.Construction(densité, valTaille + 6);

        Sim = new Simulation(this, false, valTaille, T_acc, V);
        this.setVisible(false);
        Sim.setVisible(true);
    }//GEN-LAST:event_bDemarrer_la_simulationActionPerformed

    private void RbClairseméeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbClairseméeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbClairseméeActionPerformed

    private void CbForceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbForceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbForceActionPerformed

    private void CbDirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbDirectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbDirectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbDirection;
    private javax.swing.JComboBox<String> CbForce;
    private javax.swing.JLabel L100;
    private javax.swing.JLabel L150;
    private javax.swing.JLabel L20;
    private javax.swing.JLabel L60;
    private javax.swing.JLabel LDirection;
    private javax.swing.JLabel LForce;
    private javax.swing.JLabel LHumidité;
    private javax.swing.JLabel LNormal;
    private javax.swing.JLabel LSec;
    private javax.swing.JLabel LTitre;
    private javax.swing.JLabel LTrès_sec;
    private javax.swing.JLabel LVent;
    private javax.swing.JPanel PHumidité;
    private javax.swing.JPanel PVegetation;
    private javax.swing.JPanel PVent;
    private javax.swing.JRadioButton RbClairsemée;
    private javax.swing.JRadioButton RbContinue;
    private javax.swing.JRadioButton RbEspacée;
    private javax.swing.JRadioButton RbTouffue;
    private javax.swing.JSlider SHumidite;
    private javax.swing.JButton bDemarrer_la_simulation;
    private javax.swing.JLabel bParametre;
    private javax.swing.ButtonGroup bgVegetation;
    private javax.swing.JFileChooser jFCterrain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLdev;
    private javax.swing.JLabel jLjBtelecharger;
    private javax.swing.JLabel jLnom;
    private javax.swing.JLabel jLtaille;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSTaille;
    // End of variables declaration//GEN-END:variables
}
